name: Build and test
run-name: Checking commit
on: [push]
jobs:
  build_gcc_and_test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure project
        run: cmake --preset release_gcc -G "Unix Makefiles"
      - name: Build project
        run: cmake --build --preset release_gcc
      - name: Run tests
        run: ctest --preset all
  build_clang:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure project
        run: cmake --preset release_clang -G "Unix Makefiles"
      - name: Build project
        run: cmake --build --preset release_clang
